### PR TITLE
cartIcon with count

### PR DESCRIPTION
**Pull request by manikantadevarasetty**
cartIcon with count changes

### CODE REVIEW

**Review by manikantadevarasetty — COMMENTED** [review]
cartIcon with count changes

**Review by manikantadevarasetty — COMMENTED** [review]
cartIcon with count changes

**Review by manikantadevarasetty — COMMENTED** [review]
cartIcon with count changes

**Comment by sameeranamarnath** [comment]
Kindly clone the repository and use the cloned version in your GitHub
profile in a separate repository, I'm assuming you are doing the same.

Regards
Amar.S

**Pull request closed without merging**
